# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 384e0dfc4463eb5af9d19963a36612c847a4952b31af601e9ebdf6068b3f7509d84e31e047795e14cb30f641a60735f55ac6e6cd17f2a6b79fc96ffe2eb7ab17

test:
  secret_key_base: db0fe457199553087eea24cb797d7713914dd226a95f9a290d496723b7dce59a7b066bb93bce20c0733ba0228da094d2c8c3c75d6d2bc27b7fa10c9299960cae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
